version: '3.8'

services:
  db-postgresql:
    container_name: db-postgresql
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bdkitnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-new-bdkitnet

  app:
    container_name: kitnet-app
    build:
      context: .
      dockerfile: Dockerfile
    image: kitnet-backend:latest
    depends_on:
      - db-postgresql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql:5432/bdkitnet
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - network-new-bdkitnet

volumes:
  pgdata:

networks:
  network-new-bdkitnet:
    driver: bridge
