version: '3.8'

services:
  db-postgresql:
    container_name: db-postgresql
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bdkitnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-new-bdkitnet

  app:
    container_name: kitnet-app
    build:
      context: .
      dockerfile: Dockerfile
    image: kitnet-backend:latest
    depends_on:
      - db-postgresql
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql:5432/bdkitnet
      SPRING_DATASOURCE_USERNAME: admin
      # password will be provided as a Docker secret at runtime
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # JVM options example
      JAVA_OPTS: "-Xms256m -Xmx512m"
    secrets:
      - db_password
    networks:
      - network-new-bdkitnet

volumes:
  pgdata:

networks:
  network-new-bdkitnet:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt
